// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://wykefwlganktolacsufu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind5a2Vmd2xnYW5rdG9sYWNzdWZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzczODA4MDMsImV4cCI6MjA5Mjk1NjgwM30.SiFo5_uk7iM5g7_GmYWcotek49IYLo90pTA1I74IXcE";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);